# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ComplexExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComplexExample(object):
    def setupUi(self, ComplexExample):
        ComplexExample.setObjectName("ComplexExample")
        ComplexExample.resize(551, 467)
        self.tv_ThunderGrid = QtWidgets.QTableView(ComplexExample)
        self.tv_ThunderGrid.setGeometry(QtCore.QRect(10, 10, 531, 411))
        self.tv_ThunderGrid.setObjectName("tv_ThunderGrid")

        self.retranslateUi(ComplexExample)
        QtCore.QMetaObject.connectSlotsByName(ComplexExample)

    def retranslateUi(self, ComplexExample):
        _translate = QtCore.QCoreApplication.translate
        ComplexExample.setWindowTitle(_translate("ComplexExample", "Frame"))
