# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EasyExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EasyExample(object):
    def setupUi(self, EasyExample):
        EasyExample.setObjectName("EasyExample")
        EasyExample.resize(551, 467)
        self.tv_ThunderGrid = QtWidgets.QTableView(EasyExample)
        self.tv_ThunderGrid.setGeometry(QtCore.QRect(10, 10, 531, 411))
        self.tv_ThunderGrid.setObjectName("tv_ThunderGrid")

        self.retranslateUi(EasyExample)
        QtCore.QMetaObject.connectSlotsByName(EasyExample)

    def retranslateUi(self, EasyExample):
        _translate = QtCore.QCoreApplication.translate
        EasyExample.setWindowTitle(_translate("EasyExample", "Frame"))
