# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(644, 507)
        self.pb_Exit = QtWidgets.QPushButton(MainForm)
        self.pb_Exit.setGeometry(QtCore.QRect(540, 470, 91, 31))
        self.pb_Exit.setObjectName("pb_Exit")
        self.tw_Example = QtWidgets.QTabWidget(MainForm)
        self.tw_Example.setGeometry(QtCore.QRect(10, 10, 621, 451))
        self.tw_Example.setObjectName("tw_Example")
        self.tab_EasyExample = QtWidgets.QWidget()
        self.tab_EasyExample.setObjectName("tab_EasyExample")
        self.tw_Example.addTab(self.tab_EasyExample, "")
        self.tab_ComplexExample = QtWidgets.QWidget()
        self.tab_ComplexExample.setObjectName("tab_ComplexExample")
        self.tw_Example.addTab(self.tab_ComplexExample, "")

        self.retranslateUi(MainForm)
        self.tw_Example.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "ThunderGrid Demo"))
        self.pb_Exit.setText(_translate("MainForm", "Exit"))
        self.tw_Example.setTabText(self.tw_Example.indexOf(self.tab_EasyExample), _translate("MainForm", "EasyExample"))
        self.tw_Example.setTabText(self.tw_Example.indexOf(self.tab_ComplexExample), _translate("MainForm", "ComplexExample"))
